export const theme = {
    background: "#ffffff",
    backgroundWarm: "#f7f5f1",
    onBackground: "#003220",
    onBackgroundSecondary: "#4d7063",
    divider: "#e6e4e2",
    dividerStrong: "#d3cfc8",
    brand: "#00a86b",
    brandVariant: "#009760",
    brandSoft: "#e6f5ee",
    brandDark: "#00522e",
    highlight: "#8f00ff",
    onBrand: "#ffffff",
    fontFamily: "Inter, system-ui, -apple-system, sans-serif",
};
